# Generated by Django 4.2.6 on 2023-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sno_capital_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='Cno',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='Sno',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
